## Demonstração - Pytorch

### Tensors

In [2]:
import torch
import numpy as np

#Inicialização diretamente com dados - tipo inferido automaticamente
data = [[1, 2],[3, 4]]

x_data = torch.tensor(data)
print(x_data)

#Inicialização de um NumPy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

print(x_np)

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]])


In [2]:
#Cria tensor com shape específico e com valores 1.
#Shape (2, 3)
ones_tensor = torch.ones(2,3)
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [3]:
#Cria tensor com shape específico e com valores 0.
#Shape (3, 5)
zeros_tensor = torch.zeros(3,5)
zeros_tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [4]:
#concatenação de tensors
torch.cat([ones_tensor, ones_tensor], dim=0)


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [5]:
#multiplicação de tensors

ones_tensor * 2

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [10]:
# Cria tensor com shape específico e com valores aleaórios.

#Shape (10, 3)
x = torch.randn(10, 3)
print(x)

#Shape(10, 2)
y = torch.randn(10, 2)
print(y)


tensor([[ 0.0534,  1.1075, -0.9374],
        [ 1.0226, -0.3059,  0.8400],
        [ 0.4347, -0.2652, -1.5642],
        [-1.3108, -1.1800, -0.3074],
        [ 0.2132, -1.1800, -1.6180],
        [ 0.7670,  1.3757,  1.1137],
        [-0.4538,  0.4715, -0.8006],
        [ 0.4419,  0.8488,  0.1905],
        [-0.7777, -0.7594, -0.4455],
        [-1.0569, -0.1340, -0.5088]])
tensor([[-0.3648, -0.2099],
        [ 1.6840,  0.7217],
        [-0.0096,  0.7985],
        [-0.4114,  0.3050],
        [ 1.0769, -0.3420],
        [ 0.2773,  2.6116],
        [ 0.7681,  1.7211],
        [-1.3204, -0.2735],
        [-0.6515,  0.6538],
        [ 1.0792, -0.5130]])


In [11]:
#Atributos de um tensor

print(f"Shape do tensor: {x.shape}")
print(f"Datatype do tensor: {x.dtype}")
print(f"Dispositivo onde o tensor está armazenado: {x.device}")

Shape do tensor: torch.Size([10, 3])
Datatype do tensor: torch.float32
Dispositivo onde o tensor está armazenado: cpu


In [9]:
# Movendo o tensor para a GPU se disponível 
if torch.cuda.is_available():
    x = x.to('cuda')
    
print(f"Dispositivo onde o tensor está armazenado: {x.device}")

Dispositivo onde o tensor está armazenado: cuda:0


### Manipulação de tensor 

As operações são similares a um Np-array


In [12]:
print(x)
print()
print('Primeira linha: ', x[0,:])
print('Primeira coluna: ', x[:, 0])
print('Ultima coluna:', x[:, -1])


tensor([[ 0.0534,  1.1075, -0.9374],
        [ 1.0226, -0.3059,  0.8400],
        [ 0.4347, -0.2652, -1.5642],
        [-1.3108, -1.1800, -0.3074],
        [ 0.2132, -1.1800, -1.6180],
        [ 0.7670,  1.3757,  1.1137],
        [-0.4538,  0.4715, -0.8006],
        [ 0.4419,  0.8488,  0.1905],
        [-0.7777, -0.7594, -0.4455],
        [-1.0569, -0.1340, -0.5088]])

Primeira linha:  tensor([ 0.0534,  1.1075, -0.9374])
Primeira coluna:  tensor([ 0.0534,  1.0226,  0.4347, -1.3108,  0.2132,  0.7670, -0.4538,  0.4419,
        -0.7777, -1.0569])
Ultima coluna: tensor([-0.9374,  0.8400, -1.5642, -0.3074, -1.6180,  1.1137, -0.8006,  0.1905,
        -0.4455, -0.5088])


# Criando modelos

## Primeiro modelo

Aqui é apresentado um exemplo simples que utiliza uma camada completamente conectada.

Para acelerar as operações na rede neural, nós a movemos para a GPU, se disponível.

In [22]:
from torch import nn
import torch.nn.functional as F

# Construi uma camada fully connected
#torch.nn.Linear(in_features, out_features, bias=True, device=None, dtype=None)
linear = nn.Linear(3, 2)

print ('w: ', linear.weight)
print ('b: ', linear.bias)

w:  Parameter containing:
tensor([[-0.5470,  0.4186, -0.3346],
        [ 0.2358, -0.2896,  0.0639]], requires_grad=True)
b:  Parameter containing:
tensor([-0.2415,  0.3554], requires_grad=True)


In [23]:
# Pega a GPU ou CPU para treinamento.
device = "cuda" if torch.cuda.is_available() else "cpu"

print("Usando {}".format(device))

Usando cuda


In [56]:
linear = linear.to(device)

x = x.to(device)

#Operação - Forward.
pred = linear(x)
pred

#x, tensor criado acima, representa as features de entrada
#y, tensor criado acima, representa os valores alvo

tensor([[ 0.5067, -0.0126],
        [-1.2099,  0.7388],
        [-0.0668,  0.4348],
        [ 0.0844,  0.3683],
        [-0.3107,  0.6440],
        [-0.4577,  0.2091],
        [ 0.4720,  0.0607],
        [-0.1916,  0.2260],
        [ 0.0150,  0.3634],
        [ 0.4508,  0.1124]], device='cuda:0', grad_fn=<AddmmBackward0>)

In [57]:
# Constroi a função de perda e otimização 
criterion = nn.MSELoss()

# Otimizador
optimizer = torch.optim.Adam(linear.parameters(), lr=0.001)


In [216]:
#Manda o y para a gpu
y = y.to(device)

# Computa a perda.
loss = criterion(pred, y)
print('Perda: ', loss.item())

# Propaga os erros (backpropagation) e atualiza os pesos
loss.backward()
optimizer.step() # 1-passo do 'gradient descent'

# Imprime a perda depois de 1 passo do gradient descent.
pred = linear(x)
loss = criterion(pred, y)
print('Perda depois de 1 passo de otimização : ', loss.item())

#Mais um passo - backpropagation e atualização de pesos
loss.backward()
optimizer.step()

# Imprime a perda depois de 2 passos do gradient descent.
pred = linear(x)
loss = criterion(pred, y)
print('Perda depois de 2 passos de otimização : ', loss.item())

Perda:  0.7464990019798279
Perda depois de 1 passo de otimização :  0.7459738850593567
Perda depois de 2 passos de otimização :  0.7454549670219421
